### ISSUE TITLE
启动node服务有问题看这里

### ISSUE THREAD

**Issue by mynameisjohnahahah** [wwenj/tripRecord#11]
1. 首先把文件里的node_modules删除重新下载一次(可能不需要，不过我还是这么做了)

2. 找到文件所有的mysql.createPool，把参数改成你自己数据库的参数

3. npm start 或者 set DEBUG=myapp:* npm start

**Comment by mynameisjohnahahah** [comment]
导入表的问题看[这个](https://github.com/wwenj/tripRecord/issues/9) 才能启动服务

**Comment by wwenj** [comment]
很棒棒哦😁

**Comment by 673523000** [comment]
老哥做的不错哦


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 王文健 <notifications@github.com>
发送时间: 2019年6月12日 11:04
收件人: wwenj/tripRecord <tripRecord@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[wwenj/tripRecord] 启动node服务有问题看这里 (#11)




很棒棒哦😁

**Comment by webwhy** [comment]
老哥厉害，我自己弄了两天，终于搞懂了一丢丢

**Comment by Ezoio** [comment]
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myapp@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\imi\AppData\Roaming\npm-cache\_logs\2019-06-20T14_33_50_815Z-debug.log

**Comment by Ezoio** [comment]
**首先把文件里的node_modules删除重新下载一次(可能不需要，不过我还是这么做了)**

就是删掉 然后重新 npm  install 
然后再                    npm start  就可以了

**Comment by Ezoio** [comment]
多谢楼主！

**Comment by Sashimi1125** [comment]
跨域问题怎么破

**Comment by pangpangchen** [comment]
set DEBUG=myapp:* npm start进行这个命令之后，
Set-Variable : 找不到接受实际参数“start”的位置
所在位置 行:1 字符: 1
就会有这个错误，而且网上也找不到类似的错误
